### ISSUE TITLE
Rest API - User - Upload Avartar

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG-Obsolete#459]
- **Requirement**
Develop a new endpoint for UserController: POST /api/user/{userId}/uploadAvartar

- **Reference**
POST /api/organization/{organizationId}/uploadLogo

**Comment by arpitsrm** [comment]
Submitted PR.

**Comment by arpitsrm** [comment]
@Code4SocialGood :  Submitted PR #504

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-services#14
