### ISSUE TITLE
My Profile Page - Remove Image

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG-Obsolete#460]
- **Web Path**
Home Page -> John Doe -> My Profile

- **Requirement**
1. Remove "Under Constriction" image
2. Remove Upload button

- **Screen Shot**

![image](https://cloud.githubusercontent.com/assets/24813620/23680774/13114f80-0352-11e7-9eba-6971bffa1cc3.png)

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-web#57

**Comment by sabrinadowla14** [comment]
Hi Jenny,


I am having flu from last week. Not able to work on anything. I would like
to take some time from you. Please let me know if that is ok.

Thanks,

Sabrina
