### ISSUE TITLE
My Profile Page - Text Fields

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG-Obsolete#461]
- **Web Path**
Home Page -> John Doe -> My Profile

- **Requirement**
When you click on the text fields, the label should move up. 
See: http://materializecss.com/forms.html

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-web#56

**Comment by sabrinadowla14** [comment]
Hi Jenny,

I am having following error.

[image: Inline image 1]


[image: Inline image 2]

Thanks,

Sabrina
