### ISSUE TITLE
Rest API - User - Upload Resume

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG-Obsolete#464]
Requirement
Develop a new endpoint for UserController: POST /api/user/{userId}/uploadResume

Reference
POST /api/organization/{organizationId}/uploadLogo

**Comment by arpitsrm** [comment]
Submitted PR. Please Review!

**Comment by arpitsrm** [comment]
@Code4SocialGood  :  Submitted PR #504

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-services#13
